### ISSUE TITLE
Requires Ruby1.9.2?

### ISSUE THREAD

**Issue by Sepero** [hubsmoke/bro#35]
According the website
"bro is meant to work out of the box for any machine running Ruby 1.8.7+"

When trying to install on Ubuntu 12.04 LTS, this result:

```
# gem install bropages
Fetching: json_pure-1.8.1.gem (100%)
Fetching: highline-1.6.20.gem (100%)
Fetching: commander-4.1.5.gem (100%)
Fetching: mime-types-2.1.gem (100%)
ERROR:  Error installing bropages:
        mime-types requires Ruby version >= 1.9.2.
```

**Comment by zachlysobey** [comment]
I am still seeing this issue

    ERROR:  Error installing bropages:
	mime-types requires Ruby version >= 1.9.2.

    $ ruby -v
    ruby 1.8.7 (2012-02-08 patchlevel 358) [universal-darwin12.0]
