### ISSUE TITLE
'command isn't in our database' for every query

### ISSUE THREAD

**Issue by jonascarpay** [hubsmoke/bro#65]
For example; `The curl command isn't in our database.`

Is there a way I can troubleshoot the issue? I have made sure I'm on the most recent version of gem/ruby and bro and I have verified that there are no network issues.

**Comment by hubsmoke** [comment]
Can you access http://bropages.org/curl.json

**Comment by jonascarpay** [comment]
Yes
```
➜  ~ curl http://bropages.org/curl.json | tail -b 1
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  5188    0  5188    0     0  13787      0 --:--:-- --:--:-- --:--:-- 13908
":"2015-09-22T22:51:43.000Z","id":477,"up":1,"down":1},{"cmd":"curl","msg":"# your_comment_here\nman curl","updated_at":"2016-05-31T20:58:47.000Z","id":1283,"up":1,"down":2},{"cmd":"curl","msg":"# Download http://test.com/file.txt and print it to stdout. \ncurl -o - http://test.com/file.txt","updated_at":"2015-11-16T00:19:10.000Z","id":116,"up":1,"down":5},{"cmd":"curl","msg":"# your_comment_here\ncurl\nls\ngit\nwget\ndd\ndu\ncal\nln\nlink","updated_at":"2016-09-01T03:27:46.000Z","id":251,"up":2,"down":54}]%

➜  ~ bro curl
The curl command isn't in our database.

	* Typing bro add will let you add curl to our database!

	* There's nothing to lose by typing bro add, it will just launch an
editor with instructions.

	* Need help? Visit http://bropages.org/help
```

**Comment by hubsmoke** [comment]
What do

echo $HTTP_PROXY
And
echo $http_proxy

Output?

If it's not a network issue it might be a permissions issue since the
program reads from the ~/.bro file in your home directory. I haven't tested
what happens when that isn't writeable

If none of these produce results next thing I would do is write a small
tester ruby script that uses the Net::HTTP library to make a request and
see what happens

What's your ruby version and your OS?

**Comment by jonascarpay** [comment]
Neither are defined:
```
➜  ~ echo $HTTP_PROXY

➜  ~ echo $http_proxy

```

I don't think it's a permissions thing either:
```
➜  ~ ls -l .bro
-rwxrwxrwx  1 jmc  staff  9 Oct 18 15:30 .bro
➜  ~ bro curl
The curl command isn't in our database.
```

I'm not familiar with ruby, but I slapped together this quick script from an example:
```ruby
require 'net/http'
require 'uri'

uri_ref = URI.parse("http://google.com/")
uri_bro = URI.parse("http://bropages.org/curl.json")

Net::HTTP.get_print(uri_ref)
Net::HTTP.get_print(uri_bro)
```
Which gives correct responses for both URLs.

I'm running OS X with ruby and gem installed through homebrew:
```
➜  ~ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.11.6
BuildVersion:	15G31
➜  ~ ruby -v
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]
➜  ~ gem -v
2.5.1
```

**Comment by hubsmoke** [comment]
I'm going to check the site's logs to see if I see your requests coming
through. I'm going to assume you were making requests for curl.json at 9
Oct 18 15:30

Can you also trying making a request for 'bro testing-bropages-error'? That
will help too. Only do that through the bropages gem

**Comment by jonascarpay** [comment]
Alright, I just made a single request. Note that my times are in GMT+1, so my 15:30 is 6:30 PST

**Comment by hubsmoke** [comment]
Thanks Jonas I'll take a look and report back

**Comment by hubsmoke** [comment]
Hey Jonas, I see no request for 'testing-bropages-error' in my logs. I can
only conclude that there is some hard to debug network issue.

Do you have the BROPAGES_URL environment variable set? If so try unsetting
it, we recently changed IP addresses.

**Comment by jonascarpay** [comment]
So I was messing around in irb when this happened:
```ruby
irb(main):007:0> RestClient.get("http://bropages.org/curl.json")
Netrc::Error: Permission bits for '/Users/jmc/.netrc' should be 0600, but are 640
```
and sure enough
```
➜  ~ ls -l .netrc
-rw-r-----  1 jmc  staff  101 Mar 16  2016 .netrc
➜  ~ bro curl
The curl command isn't in our database.
...
➜  ~ chmod 600 .netrc
➜  ~ ls -l .netrc
-rw-------  1 jmc  staff  101 Mar 16  2016 .netrc
➜  ~ bro curl
26 entries for curl -- submit your own example with "bro add curl"
```
Anyway, I'm glad we figured it out. Thank you for your help!

**Comment by hubsmoke** [comment]
Thanks for reporting. This goes to show swallowing exceptions is bad. I
will have to update the code to give a better error
